RealEstateApplication/StoreApp/Models/Pagination.cs
namespace RealEstateApp.Models
{
    public class Pagination
    {
        public int TotalItems { get; set; }   
        public int ItemsPerPage { get; set; }   
        public int CurrentPage { get; set; } 

        public int TotalPage => (int)Math.Ceiling((decimal)TotalItems/ItemsPerPage);
    }
}

RealEstateApplication/StoreApp/Models/ProductListViewModel.cs
using Domain.Models;

namespace RealEstateApp.Models
{
    public class ProductListViewModel
    {
        public IEnumerable<Product> Products { get; set; } = Enumerable.Empty<Product>();
        public Pagination Pagination { get; set; } = new();

        public int TotalCount => Products.Count();
    }
}

RealEstateApplication/StoreApp/Components/ProductFeatureGroupMenuViewComponent.cs
using Application.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Components
{
    public class ProductFeatureGroupMenuViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public ProductFeatureGroupMenuViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }
        public IViewComponentResult Invoke()
        {
            var categories = _manager.ProductFeatureGroupServices.GetAllProductFeatureGroup(false);



            return View(categories);

        }

    }
}

RealEstateApplication/StoreApp/Components/ProductFeatureGroupSummaryViewComponent.cs
using Application.Interfaces;
using Microsoft.AspNetCore.Mvc;


namespace Components
{
    public class ProductFeatureGroupSummaryViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public ProductFeatureGroupSummaryViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public string Invoke()
        {
            return _manager
            .ProductFeatureGroupServices
            .GetAllProductFeatureGroup(false)
            .Count()
            .ToString();

        }

    }
}

RealEstateApplication/StoreApp/Components/ProductFeatureMenuViewComponent.cs
using Application.Interfaces;
using Microsoft.AspNetCore.Mvc;
namespace Components
{
    public class ProductFeatureMenuViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public ProductFeatureMenuViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }
        public IViewComponentResult Invoke(short id)
        {
            var productFeatureGroup = _manager.ProductFeatureGroupServices.GetOneProductFeatureGroup(id,false);
            var model = _manager.ProductFeatureServices.GetListProductFeature(productFeatureGroup.id, false);


            return View(model);
            //return View(model);

        }
    }
}

RealEstateApplication/StoreApp/Components/ProductFilterMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Components
{
    public class ProductFilterMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();

        }
    }
}

RealEstateApplication/StoreApp/Components/ProductSummaryViewComponent.cs
using Application.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Components
{
    public class ProductSummaryViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public ProductSummaryViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }
        public string Invoke()
        {

            return _manager.ProductService.GetAllProduct(false).Count().ToString();
        }

    }
}

RealEstateApplication/StoreApp/Components/ShowCaseViewComponent.cs
using Application.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Components
{
    public class ShowCaseViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;
        public ShowCaseViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public IViewComponentResult Invoke(string page = "default")
        {

            var product = _manager.ProductService.GetShowCaseProducts(false);
            return
            page.Equals("default")
            ? View(product)
            : View("List", product);
        }
    }
}

RealEstateApplication/StoreApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Controllers
{
    public class HomeController : Controller
    {   
        public IActionResult Index()
        {
            ViewData["Title"]="Welcome";
            return View ();
        }

        
    }
    
}

RealEstateApplication/StoreApp/Controllers/ProductController.cs
using Application.Interfaces;
using Domain.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using RealEstateApp.Models;

namespace Controllers
{
    public class ProductController : Controller
    {

        // private readonly RepositoryContext _context;
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index(ProductRequestParameters p )
        {
            var products= _manager.ProductService.GetAllProductsWithDetails(p);

            var pagination  = new Pagination() {
                CurrentPage=p.PageNumber,
                ItemsPerPage=p.PageSize,
                TotalItems= _manager.ProductService.GetAllProduct(false).Count()

            };
            return View(new ProductListViewModel () {
                Products=products,
                Pagination=pagination
            });

        }

        public IActionResult Get([FromRoute(Name ="id") ] int id)
        {

            var model= _manager.ProductService.GetOneProduct(id,false);

            ViewData["Title"]=model.title;
            return View(model);
        }
    }

}

RealEstateApplication/StoreApp/Controllers/ProductFeatureController.cs
using Application.Interfaces;
using Microsoft.AspNetCore.Mvc;


namespace Controllers
{
    public class ProductFeatureController : Controller
    {

        private IServiceManager _manager;

        public ProductFeatureController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var productFeatureGroup = _manager.ProductFeatureGroupServices.GetAllProductFeatureGroup(false);
            foreach (var productFeatureGroupId in productFeatureGroup)
            {

                var model = _manager.ProductFeatureServices.GetListProductFeature(productFeatureGroupId.id, false);
                return View(model);
            }

            return View();
        }
    }
}

RealEstateApplication/StoreApp/Controllers/ProductFeatureGroupController.cs
using Application.Interfaces;
using Microsoft.AspNetCore.Mvc;


namespace Controllers
{
    public class ProductFeatureGroupController : Controller
    {
        
        private IServiceManager _manager;

        public ProductFeatureGroupController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {

            var model =  _manager.ProductFeatureGroupServices.GetAllProductFeatureGroup(false);          
            return View(model);

        }
    }
}

RealEstateApplication/StoreApp/Controllers/ProductsController.cs
using Application.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace RealEstateApp.Presentation.Controllers
{
    
[Route("api/products")]
    [ApiController]
    public class ProductsController : ControllerBase
    {
        private readonly IServiceManager _manager;

        public ProductsController(IServiceManager manager)
        {
            _manager = manager;
        }

        [HttpGet]
        public IActionResult GetAllProducts()
        {
            return Ok(_manager.ProductService.GetAllProduct(false));
        }
    }

}

RealEstateApplication/StoreApp/Views/Home/Index.cshtml
@await Component.InvokeAsync("ShowCase")

RealEstateApplication/StoreApp/Views/Product/Get.cshtml
@model Product

<div class="row">
    <div class="col-md-12">
        <div class="text-center">
            <h6 class="display-6"> @Model.title</h6>

            <img class="img-fluid shadow rounded-3 p-5 my-3" src="@Model?.ImageUrl" alt="@Model?.title ">


            <p class="lead text-danger"> @Model.price.ToString()</p>

        </div>
    </div>

</div>

<div class="text-center">
    <div class="btn-group">
        <a class="btn btn-outline-secondary" asp-controller="Home" asp-action="Index">
            <i class="fa-solid fa-house"></i> Home</a>
            <form id="@Model.id" asp-page="/card" method="post" >
            
            <input type="hidden" asp-for="id">
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndRequery()">
            <button type="submit" class="btn btn-outline-secondary rounded-0" >
                <i class="fa fa-cart-plus"></i>
                Add To Cart </button>
            </form>
        <a class="btn btn-outline-secondary" asp-controller="Product" asp-action="Index"><i class="fa-solid fa-list"></i>
            Product</a>

    </div>

</div>
@section Header {
    <div>
    </div>

}

RealEstateApplication/StoreApp/Views/Product/Index.cshtml
@model ProductListViewModel

<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("ProductFeatureGroupMenu")
        @await Component.InvokeAsync("ProductFilterMenu")
        <div products="" number="3"></div>
    </div>
    <div class="col-md-9">

        <div class="row my-3 ">

            @foreach (Product prd in Model.Products)
            {
                @* <div>
            <h3> @prd.ProductName </h3>
            <p> @prd.Price </p>
            <p>
            <a href="/Product/Get/@prd.ProductId"> Get Details </a>
            </p>

            </div> *@
                <partial name="_ProductCard" model="@prd"> </partial>

            }
        </div>

        <div>
            <div page-model="@Model?.Pagination" page-action="Index" class="btn-group text-center" page-classes-enabled="true"
                page-class="btn" page-class-normal="btn-outline-dark" page-class-selected="btn-primary"></div>


        </div>



    </div>
</div>

@section Footer {

}

RealEstateApplication/StoreApp/Views/ProductFeature/Index.cshtml
@model IEnumerable<ProductFeature>

<div class="text-center my-3">
<h6 class="display-6">Product Feature </h6>

</div>

<ul class="list-group my-3">

    @foreach (var productFeature in Model)
    {
        <li class="list-group-item"> @productFeature.value </li>

    }


</ul>

RealEstateApplication/StoreApp/Views/ProductFeatureGroup/Index.cshtml
@model IEnumerable<ProductFeatureGroup>

<div class="text-center my-3">
<h6 class="display-6">Product Feature Group </h6>

</div>

<ul class="list-group my-3">

    @foreach (var productFeatureGroup in Model)
    {
        <li class="list-group-item"> @productFeatureGroup.value </li>
    }
</ul>

RealEstateApplication/StoreApp/Views/Shared/Components/ProductFeatureGroupMenu/Default.cshtml
@model IEnumerable<ProductFeatureGroup>

<div class="mt-3">
    <h6 class="lead">
        <i class="fa fa-solid fa-bars text-secondary"></i>
        Product Feature
    </h6>
</div>


<div class="my-4">
    <ul class="list-group">

        @foreach (var productFeatureGroup in Model )
        {
            <li class="list-group-item">
            @productFeatureGroup.value
                <ul class="list-group">
                    <li class="list-group-item">
                        @await Component.InvokeAsync("ProductFeatureMenu",productFeatureGroup.id)
                    </li>
                </ul>
            </li>
        }

    </ul>

</div>

RealEstateApplication/StoreApp/Views/Shared/Components/ProductFeatureMenu/Default.cshtml
@model IEnumerable<ProductFeature>

<div class="my-4">
    <ul class="list-group">
        @foreach (var productFeature in Model)
        {
            <li class="list-group-item">
                <input type="checkbox" id="checkbox @productFeature.id"/>
                @productFeature.value
            </li>
        }

    </ul>

</div>

RealEstateApplication/StoreApp/Views/Shared/Components/ProductFilterMenu/Default.cshtml
<div class="my-3">

    <h6 class="lead">
        <i class="fa fa-filter text-secondary"></i>
        Filters
    </h6>

</div>
<div class="my-2">

    <form method="get" asp-action="Index"  >
        <input type="hidden" name="productFeatureId" value="@(Context.Request.Query["productFeatureId"])" />
        <div class="form-group my-2">
            <input class="form-control" name="SearchTerm" placeholder="Search">
        </div>
        <div class="form-group my-2">
            <input class="form-control" name="MinPrice" placeholder="Min Price">
        </div>
        <div class="form-group my-2">
            <input class="form-control" name="MaxPrice" placeholder="Max Price">
        </div>

        <div class="form-group my-2">
            <button type="submit" class="btn btn-primary btn-sm"> Filter</button>

        </div>
    </form>

</div>

RealEstateApplication/StoreApp/Views/Shared/Components/ShowCase/Default.cshtml
@model IEnumerable<Product>
<div class="text-center">
    <h6  class="display-6"> Real Estate </h6>

</div>

<div class="row">

    @foreach (var prd in Model)
    {

        <partial name="_ProductCard" model="prd"> </partial>
    }

</div>

RealEstateApplication/StoreApp/Views/Shared/Components/ShowCase/List.cshtml
@model IEnumerable<Product>

<div class="mt-5 text-center border-bottom">
    <h6 class="display-6">Products</h6>
</div>

<div class="row">
    @foreach (var prd in Model)
    {
        <div class="col-md-3 my-3">
            <div class="card" style="width: 18rem;">
                @* <img class="card-img-top" src="@prd.ImageUrl" alt="Card image cap"> *@
                <div class="card-body">
                    <h5 class="card-title">@prd.title</h5>
                    <p class="card-text">@prd.price</p>
                    <a asp-action="Update" asp-controller="Product" asp-route-id="@prd.id"
                        class="btn btn-primary">Edit</a>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-between">

                        <div class="form-check form-switch">
                            <input type="hidden" name="productId" value="@prd.id" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

RealEstateApplication/StoreApp/Views/Shared/_Footer.cshtml
<div class="bg-light border-top p-3">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="lead text-center ">
                    <i class="fa-solid fa-store text-secondary display-6"></i>
                    <br />
                    <bold>Real Estate</bold>
                </div>
                <div class="text-muted text-center">
                    Real Estate App
                </div>
            </div>
            <div class="col-md-8">
                <div class="text-center text-muted my-3">
                    &copy; 2024 <br />Real Estate Project
                </div>

                <div class="text-center">
                    <div class="btn-group">
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-facebook"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-linkedin"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-youtube"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-instagram"></i>
                        </a>
                    </div>
                </div>

            </div>
            <div class="col-md-2">
                <div products="" number="6"></div>
            </div>
        </div>
    </div>
</div>

RealEstateApplication/StoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Real Estate @ViewData["Title"] </title>
    <link asp-append-version="true"  rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link asp-append-version="true" rel="stylesheet" href="~/css/site.css" />
    <link asp-append-version="true"  rel="stylesheet" href="~lib/font-awesome/css/all.css" />

</head>

<body>

    <header>
        <partial name="_Navbar"> </partial>
        @RenderSection("Header", false)
    </header>
    <div class="container">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        @RenderSection("Footer", false)
        <partial name="_Footer" />
    </footer>


    <script asp-append-version="true" src="~/lib/jquery/jquery.min.js"></script>
    <script asp-append-version="true" src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script asp-append-version="true" src="~/js/site.js"></script>
    <script asp-append-version="true" src="~/lib/font-awesome/js/all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>

RealEstateApplication/StoreApp/Views/Shared/_Navbar.cshtml
@* <a asp-controller="Home" asp-action="Index">Home</a></li>
@* <li> <a asp-controller="Home" asp-action="Privacy">Privacy</a></li> *@
@* <a asp-controller="Product" asp-action="Index">Prodcuts</a></li> *@

<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container">
        <a class="navbar-brand" href="/"> <i class="fa-solid fa-store fa-2x text-secondary"></i>
        
        </a>
       
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Product" asp-action="Index">Prodcuts(@await Component.InvokeAsync("ProductSummary") )</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

RealEstateApplication/StoreApp/Views/Shared/_Notification.cshtml
@if (TempData["info"] is not null)
{
    <div class="alert alert-info my-3" role="role">
        @TempData["info"]
    </div>

}
@if (TempData["success"] is not null)
{
    <div class="alert alert-success my-3" role="role">
        @TempData["success"]
    </div>

}
@if (TempData["danger"] is not null)
{
    <div class="alert alert-danger my-3" role="role">
        @TempData["danger"]
    </div>

}

RealEstateApplication/StoreApp/Views/Shared/_ProductCard.cshtml
@model Product

<div class="col-sm-12 col-md-4 my-2">



    <div class="card" style="width: 18rem;">
        <div class="card-header text-center">
            @Model.title

        </div>

        <img src="@Model?.ImageUrl" class="card-img-top" alt="...">

        <div class="card-body">

            <div class="card-text">
                <div class="text-danger text-center lead p-2 rounded">
                    @Model?.price.ToString("C2")

                </div>


            </div>
            @* <h5 class="card-title"></h5> *@
            <p class="card-text">@Model?.description</p>

            <div class="d-flex justify-content-center">

                <div class=" btn btn-group">

                    <a asp-action="Get" asp-controller="Product" asp-route-id="@Model?.id"
                        class="btn btn-outline-secondary rounded-2">
                        <i class="fa-solid fa-arrow-right"></i>
                         </a>

                    <form id="@Model?.id" asp-page="/card" method="post">
                        <input type="hidden" asp-for="id" />

                        @* <input type="hidden" name="returnUrl" value="/Product/Get/@Model.ProductId" /> *@
                        <input type="hidden" name="returnUrl"
                            value="@ViewContext.HttpContext.Request.PathAndRequery()" />

                        <button type="submit" class="btn btn-outline-secondary mx-1">
                            <i class="fa fa-cart-plus"> </i>

                        </button>
                        pagen
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>